defaults: &defaults
  adapter: postgresql
  username: <%= ENV['DATABASE_USER'] || ENV["POSTGRES_USER"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *defaults
  database: <%= ENV.fetch('DATABASE_NAME', 'timeoverflow_development') %>

test:
  <<: *defaults
  database: timeoverflow_test
  host: localhost
  password: <%= ENV['DATABASE_PASSWORD'] || ENV["POSTGRES_PASSWORD"] %>

production:
  <<: *defaults
  url: <%= ENV['DATABASE_URL'] %>
